#!/usr/bin/env bash
# Generate web/types.d.ts from openapi.json with openapi-typescript (free, MIT), pinned.
#   bash scripts/make_types.sh          # needs Node and internet the first time (npx downloads the tool)
# The first line of the output records the sha256 of openapi.json, so tests/contract can tell if it is stale
# without needing the tool or the network.
set -euo pipefail
cd "$(dirname "$0")/.."
TOOL="openapi-typescript@7.13.0"
SHA="$(shasum -a 256 openapi.json | cut -d' ' -f1)"
npx --yes "$TOOL" openapi.json -o web/types.d.ts
{ printf '// Generated by scripts/make_types.sh (%s) from openapi.json. DO NOT EDIT BY HAND.\n// openapi.json sha256: %s\n// Research prototype for clinician evaluation; not a marketed medical device; not for unsupervised clinical use.\n' "$TOOL" "$SHA"; cat web/types.d.ts; } > web/types.d.ts.tmp
mv web/types.d.ts.tmp web/types.d.ts
echo "wrote web/types.d.ts ($(wc -l < web/types.d.ts | tr -d ' ') lines)"
