// Generated by scripts/make_types.sh (openapi-typescript@7.13.0) from openapi.json. DO NOT EDIT BY HAND.
// openapi.json sha256: 1a569cdb7241b17c554c335188a2b360eea6fb52f72d4a8d6e073537625cc31f
// Research prototype for clinician evaluation; not a marketed medical device; not for unsupervised clinical use.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommend */
        post: operations["recommend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbstainNoticeV1 */
        AbstainNoticeV1: {
            /**
             * Option
             * @enum {string}
             */
            option: "SGLT2i" | "DPP4i" | "SU";
            /** Propensity */
            propensity?: number | null;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Threshold */
            threshold?: number | null;
            /** Why */
            why: string;
        };
        /** AnswerCardV1 */
        AnswerCardV1: {
            /**
             * Abstain
             * @default []
             */
            abstain: components["schemas"]["AbstainNoticeV1"][];
            /**
             * Cautions
             * @description 'check first' rules that fired for an option the rules left, with rule ID and source (P24)
             * @default []
             */
            cautions: components["schemas"]["RuleHitV1"][];
            /** Claims */
            claims: components["schemas"]["CardClaimV1"][];
            /**
             * Comparator
             * @enum {string}
             */
            comparator: "SGLT2i" | "DPP4i" | "SU";
            /**
             * Decision
             * @default Decision support only. The clinician decides.
             */
            decision: string;
            /**
             * Drivers
             * @default {}
             */
            drivers: {
                [key: string]: components["schemas"]["DriverV1"][];
            };
            /**
             * Dropped Claims
             * @description claims of the model's draft the citation check dropped (the rest were kept)
             * @default 0
             */
            dropped_claims: number;
            /** Effects */
            effects: components["schemas"]["EffectRowV1"][];
            /** Evidence Levels */
            evidence_levels: components["schemas"]["EvidenceLevelV1"][];
            /** Excluded */
            excluded: components["schemas"]["RuleHitV1"][];
            /**
             * Failed Checks
             * @description the output checks (plan 8.10) the model's draft failed; empty on a timeout or when the model was not used
             * @default []
             */
            failed_checks: ("parse" | "citations" | "numbers" | "dose_threshold" | "excluded_option" | "insufficient_wording" | "identifier_causal")[];
            /**
             * Fallback Reason
             * @description a CODE (TIMEOUT, UNREACHABLE, INVALID_JSON, GUARD_NUMBERS, ...), never text from the model
             */
            fallback_reason?: string | null;
            /**
             * Fallback Used
             * @description true when the local model was asked and the template answered instead
             * @default false
             */
            fallback_used: boolean;
            /**
             * Intended Use
             * @default Research prototype for clinician evaluation; not a marketed medical device; not for unsupervised clinical use.
             */
            intended_use: string;
            /**
             * Limitations
             * @description one or two sentences from the local model, only when it passed the output guards
             */
            limitations?: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "template" | "ollama";
            /** Patient Summary */
            patient_summary: string;
            /** Question */
            question: string;
            /**
             * Question Context
             * @description one sentence from the local model, only when it passed the output guards
             */
            question_context?: string | null;
            /** Request Id */
            request_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            versions: components["schemas"]["Versions"];
        };
        /**
         * AnswerDraftV1
         * @description What the LLM may return (and nothing else).
         */
        AnswerDraftV1: {
            /** Evidence Summary */
            evidence_summary: components["schemas"]["ClaimV1"][];
            /**
             * Insufficient
             * @default false
             */
            insufficient: boolean;
            /**
             * Insufficient Reason
             * @description one sentence, when insufficient is true
             * @default null
             */
            insufficient_reason: string | null;
            /** Limitations */
            limitations: string;
            /** Question Context */
            question_context: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /**
         * AskRequestV1
         * @description POST /api/v1/ask. `schema_version` is required here (the one payload every client builds).
         */
        AskRequestV1: {
            /**
             * Mode
             * @default template
             * @enum {string}
             */
            mode: "template" | "ollama";
            patient: components["schemas"]["PatientV1"];
            /** Question */
            question: string;
            /**
             * Request Id
             * @description the client's trace ID (1-64 of A-Z a-z 0-9 - _)
             */
            request_id: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0";
        };
        /** CardClaimV1 */
        CardClaimV1: {
            /** Citations */
            citations: components["schemas"]["CitationV1"][];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Text */
            text: string;
        };
        /**
         * CausalOutputV1
         * @description The engine's CausalOutput, unchanged (applicable, intervention, outcome, options, comparisons,
         *     assumptions, bmi_category, versions, decision, intended_use), with options that may carry drivers.
         */
        CausalOutputV1: {
            /**
             * Applicable
             * @enum {string}
             */
            applicable: "APPLICABLE" | "NOT_APPLICABLE";
            /** Assumptions */
            assumptions: string[];
            /** Bmi Category */
            bmi_category: string;
            /**
             * Comparisons
             * @default []
             */
            comparisons: components["schemas"]["Comparison"][];
            /**
             * Decision
             * @default Decision support only. The clinician decides.
             */
            decision: string;
            /**
             * Intended Use
             * @default Research prototype for clinician evaluation; not a marketed medical device; not for unsupervised clinical use.
             */
            intended_use: string;
            /**
             * Intervention
             * @default Add one of three options to metformin: SGLT2 inhibitor, DPP-4 inhibitor or sulfonylurea
             */
            intervention: string;
            /**
             * Not Applicable Reasons
             * @default []
             */
            not_applicable_reasons: string[];
            /** Options */
            options: components["schemas"]["OptionV1"][];
            /**
             * @default {
             *       "direction": "negative = HbA1c falls (better glucose control)",
             *       "name": "Change in HbA1c at 6 months",
             *       "unit": "percentage points of HbA1c (%)"
             *     }
             */
            outcome: components["schemas"]["Outcome"];
            /** Request Id */
            request_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            versions: components["schemas"]["Versions"];
        };
        /** CitationV1 */
        CitationV1: {
            /** Chunk Id */
            chunk_id: string;
            /**
             * Label
             * @description e.g. 'WHO 2018, p.12'
             */
            label: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** ClaimV1 */
        ClaimV1: {
            /**
             * Chunk Ids
             * @description the retrieved passages that support the claim; an uncited claim is dropped by the output guards
             */
            chunk_ids: string[];
            /** Claim */
            claim: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** Comparison */
        Comparison: {
            difference: components["schemas"]["Interval"];
            /** First */
            first: string;
            /** Second */
            second: string;
        };
        /** Confidence */
        Confidence: {
            /**
             * Interval Level
             * @default 0.95
             */
            interval_level: number;
            /** Method */
            method: string;
            /** Overlap Threshold */
            overlap_threshold: number;
            /** Propensity */
            propensity: number;
        };
        /** Cost */
        Cost: {
            /** As Of Date */
            as_of_date?: string | null;
            /** Inr Per Month */
            inr_per_month: number | null;
            /** Label */
            label: string;
            /** Source */
            source?: string | null;
        };
        /**
         * DriverV1
         * @description One SHAP driver of one option's estimate: 'the estimate is larger/smaller for patients with ...'
         *     (never a cause). `contribution` is in HbA1c percentage points, signed.
         */
        DriverV1: {
            /**
             * Ci95
             * @description 95% interval, when computed (P25)
             */
            ci95?: [
                number,
                number
            ] | null;
            /** Contribution */
            contribution: number;
            /** Feature */
            feature: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Value
             * @description this patient's value for the feature
             */
            value: number | boolean | string;
        };
        /** EffectRowV1 */
        EffectRowV1: {
            /**
             * Caution
             * @description a 'check first' rule fired for this option
             * @default false
             */
            caution: boolean;
            /**
             * Cost Label
             * @description 'price unavailable' until a verified price exists
             */
            cost_label: string;
            /** @description 6-month change, percentage points, with its 95% interval */
            hba1c_change?: components["schemas"]["Interval"] | null;
            hypo_risk_pct?: components["schemas"]["Interval"] | null;
            /**
             * Option
             * @enum {string}
             */
            option: "SGLT2i" | "DPP4i" | "SU";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Status
             * @enum {string}
             */
            status: "ESTIMATED" | "INSUFFICIENT_EVIDENCE" | "EXCLUDED";
            /** @description null for the comparator itself */
            vs_comparator?: components["schemas"]["Interval"] | null;
            weight_change_kg?: components["schemas"]["Interval"] | null;
        };
        /**
         * EligibleOptionsV1
         * @description What the rules leave: removed options never reach the causal engine.
         */
        EligibleOptionsV1: {
            /** Caution */
            caution: components["schemas"]["RuleHitV1"][];
            /** Eligible */
            eligible: ("SGLT2i" | "DPP4i" | "SU")[];
            /** Excluded */
            excluded: components["schemas"]["RuleHitV1"][];
            /**
             * Rules Version
             * @description e.g. rules.csv@<git-sha>
             */
            rules_version: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** ErrorV1 */
        ErrorV1: {
            /**
             * Error
             * @default invalid_request
             * @constant
             */
            error: "invalid_request";
            /**
             * Intended Use
             * @default Research prototype for clinician evaluation; not a marketed medical device; not for unsupervised clinical use.
             */
            intended_use: string;
            /** Message */
            message: string;
            /** Problems */
            problems: {
                [key: string]: unknown;
            }[];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** EvidenceBundleV1 */
        EvidenceBundleV1: {
            /** Chunks */
            chunks: components["schemas"]["EvidenceChunkV1"][];
            /** Index Version */
            index_version: string;
            /**
             * Reason
             * @description why, when status is INSUFFICIENT_EVIDENCE
             * @default null
             */
            reason: string | null;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Status
             * @enum {string}
             */
            status: "OK" | "INSUFFICIENT_EVIDENCE";
        };
        /** EvidenceChunkV1 */
        EvidenceChunkV1: {
            /** Chunk Id */
            chunk_id: string;
            /** Licence */
            licence: string;
            /**
             * Page
             * @description null for a web page
             * @default null
             */
            page: number | null;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            scores: components["schemas"]["ScoresV1"];
            /** Section */
            section: string;
            /** Source */
            source: string;
            /** Text */
            text: string;
            /** Version */
            version: string;
        };
        /** EvidenceLevelV1 */
        EvidenceLevelV1: {
            /**
             * Level
             * @enum {string}
             */
            level: "Moderate" | "Low" | "Insufficient";
            /**
             * Option
             * @enum {string}
             */
            option: "SGLT2i" | "DPP4i" | "SU";
            /**
             * Reason
             * @description the one-line reason, from the TEAM-SET rule in params.yaml
             */
            reason: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** GuardCheckV1 */
        GuardCheckV1: {
            /**
             * Id
             * @enum {string}
             */
            id: "scope" | "identifier" | "red_flag" | "injection" | "range" | "length_language" | "dose_request";
            /**
             * Result
             * @enum {string}
             */
            result: "PASS" | "BLOCK";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /**
         * GuardResultV1
         * @description Seven input checks, in order. A BLOCK stops the request with a notice; the matched word is never shown.
         */
        GuardResultV1: {
            /**
             * Blocked Reason
             * @description plain English; never repeats the matched word
             * @default null
             */
            blocked_reason: string | null;
            /** Checks */
            checks: components["schemas"]["GuardCheckV1"][];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Status
             * @enum {string}
             */
            status: "PASS" | "BLOCK";
        };
        /**
         * GuardedDraftV1
         * @description The output guards' verdict (plan 8.10). FALLBACK = use the template wording instead; ABSTAIN = no claim
         *     survived; BLOCK = an identifier or causal wording about a driver.
         */
        GuardedDraftV1: {
            /** Checks */
            checks: components["schemas"]["OutputCheckV1"][];
            /**
             * @description the kept claims; null on FALLBACK, ABSTAIN or BLOCK
             * @default null
             */
            draft: components["schemas"]["AnswerDraftV1"] | null;
            /**
             * Dropped Claims
             * @default 0
             */
            dropped_claims: number;
            /**
             * Fallback Reason
             * @default null
             */
            fallback_reason: string | null;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Status
             * @enum {string}
             */
            status: "PASS" | "FALLBACK" | "ABSTAIN" | "BLOCK";
        };
        /** HealthV1 */
        HealthV1: {
            /** Engine */
            engine: string;
            /**
             * Intended Use
             * @default Research prototype for clinician evaluation; not a marketed medical device; not for unsupervised clinical use.
             */
            intended_use: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * Interval
         * @description Expected 6-month change in HbA1c (percentage points) with its 95% interval.
         */
        Interval: {
            /** Ci High */
            ci_high: number;
            /** Ci Low */
            ci_low: number;
            /**
             * Level
             * @default 0.95
             */
            level: number;
            /** Value */
            value: number;
        };
        /**
         * LLMRequestV1
         * @description What the prompt builder hands to a provider (the fields of the 8.9 template). Temperature 0 and a
         *     4,096-token context are provider settings, not part of this contract.
         */
        LLMRequestV1: {
            causal_output: components["schemas"]["CausalOutputV1"];
            /** Drivers */
            drivers: {
                [key: string]: components["schemas"]["DriverV1"][];
            };
            evidence: components["schemas"]["EvidenceBundleV1"];
            /** Excluded By Rules */
            excluded_by_rules: components["schemas"]["RuleHitV1"][];
            /**
             * Max Claims
             * @default 4
             */
            max_claims: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "template" | "ollama";
            /**
             * Patient Summary
             * @description e.g. '52 y, M, HbA1c 8.6%, eGFR 72, BMI 27.1 (overweight)'
             */
            patient_summary: string;
            /** Question */
            question: string;
            /** Request Id */
            request_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /**
         * OptionV1
         * @description The engine's OptionOut, unchanged, plus drivers.
         */
        OptionV1: {
            /**
             * Arm
             * @enum {string}
             */
            arm: "SGLT2i" | "DPP4i" | "SU";
            confidence?: components["schemas"]["Confidence"] | null;
            cost: components["schemas"]["Cost"];
            /**
             * Drivers
             * @default []
             */
            drivers: components["schemas"]["DriverV1"][];
            effect?: components["schemas"]["Interval"] | null;
            /** Example Molecule */
            example_molecule: string;
            /** Insufficient Reason */
            insufficient_reason?: string | null;
            /** Name */
            name: string;
            /** Safety */
            safety: components["schemas"]["SafetyNote"][];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            secondary?: components["schemas"]["Secondary"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "estimate" | "insufficient_evidence" | "excluded";
        };
        /** Outcome */
        Outcome: {
            /**
             * Direction
             * @default negative = HbA1c falls (better glucose control)
             */
            direction: string;
            /**
             * Name
             * @default Change in HbA1c at 6 months
             */
            name: string;
            /**
             * Unit
             * @default percentage points of HbA1c (%)
             */
            unit: string;
        };
        /** OutputCheckV1 */
        OutputCheckV1: {
            /**
             * Id
             * @enum {string}
             */
            id: "parse" | "citations" | "numbers" | "dose_threshold" | "excluded_option" | "insufficient_wording" | "identifier_causal";
            /**
             * Result
             * @enum {string}
             */
            result: "PASS" | "FAIL";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /**
         * PatientV1
         * @description One patient. Units: years, HbA1c %, eGFR mL/min/1.73m², BMI kg/m², waist cm, glucose mg/dL.
         */
        PatientV1: {
            /**
             * Age
             * @description years
             */
            age: number;
            /** Ascvd */
            ascvd: boolean;
            /**
             * Bmi
             * @description BMI, kg/m²
             */
            bmi: number;
            /** Ckd */
            ckd: boolean;
            /**
             * Cost Concern
             * @default false
             */
            cost_concern: boolean;
            /**
             * Duration Years
             * @description years since type 2 diabetes was diagnosed
             */
            duration_years: number;
            /**
             * Egfr
             * @description eGFR, mL/min/1.73m²
             */
            egfr: number;
            /**
             * Glucose Mg Dl
             * @description NOT used in the estimate
             */
            glucose_mg_dl?: number | null;
            /**
             * Hba1C Pct
             * @description HbA1c, %
             */
            hba1c_pct: number;
            /** Heart Failure */
            heart_failure: boolean;
            /**
             * On Metformin
             * @description must be true; the scope guard blocks false
             */
            on_metformin: boolean;
            /** Past Dka */
            past_dka: boolean;
            /** Past Hypo */
            past_hypo: boolean;
            /** Past Pancreatitis */
            past_pancreatitis: boolean;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Sex
             * @enum {string}
             */
            sex: "F" | "M";
            /**
             * Type1
             * @description type 1 diabetes: out of scope; the input guard blocks it
             */
            type1: boolean;
            /**
             * Waist Cm
             * @description display only
             */
            waist_cm?: number | null;
        };
        /**
         * RecommendRequestV1
         * @description POST /api/v1/recommend: the causal engine alone, for one patient.
         */
        RecommendRequestV1: {
            patient: components["schemas"]["PatientV1"];
            /** Request Id */
            request_id: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0";
        };
        /** RuleHitV1 */
        RuleHitV1: {
            /**
             * Option
             * @enum {string}
             */
            option: "SGLT2i" | "DPP4i" | "SU";
            /**
             * Rule Id
             * @description a rule id from data/rules.csv, e.g. R04
             */
            rule_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Source
             * @description label and section, e.g. 'JANUVIA US prescribing information, Sec 2.2'
             */
            source: string;
        };
        /** SafetyNote */
        SafetyNote: {
            /**
             * Action
             * @enum {string}
             */
            action: "EXCLUDE" | "CAUTION";
            /** Condition */
            condition: string;
            /** Message */
            message: string;
            /** Rule Id */
            rule_id: string;
            /**
             * Rule Status
             * @enum {string}
             */
            rule_status: "VERIFIED" | "UNVERIFIED";
            /** Section */
            section: string;
            /** Source */
            source: string;
        };
        /** ScoresV1 */
        ScoresV1: {
            /** Bm25 */
            bm25: number;
            /**
             * Dense
             * @description null until the dense index exists (P18)
             * @default null
             */
            dense: number | null;
            /** Rrf */
            rrf: number;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /**
         * Secondary
         * @description FR7: this patient's expected 6-month weight change and hypoglycaemia risk under the option.
         */
        Secondary: {
            hypo_risk_pct: components["schemas"]["Interval"];
            /**
             * Note
             * @default Secondary outcomes from the same synthetic cohort and method; the clinician decides.
             */
            note: string;
            weight_change_kg: components["schemas"]["Interval"];
        };
        /** Versions */
        Versions: {
            /** Cohort */
            cohort: string;
            /** Engine */
            engine: string;
            /** Params */
            params: string;
            /** Params Sha */
            params_sha: string;
            /** Rules Sha */
            rules_sha: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerCardV1"];
                };
            };
            /** @description The request did not match the contract. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorV1"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthV1"];
                };
            };
        };
    };
    recommend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CausalOutputV1"];
                };
            };
            /** @description The request did not match the contract. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorV1"];
                };
            };
        };
    };
}
